# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'QRCode_iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'OpenCV', '~> 3.4.1'

end
